### ISSUE TITLE
Identify assurance claims

### ISSUE THREAD

**Issue by SethRedwine** [SethRedwine/CSCI8420-TeamASJY#10]
Using security requirements, identify five assurance claims. Claims should have an entity, a critical property of the entity, and a value for the property and related uncertainty.

Ex. 
Entity:      The system
Property:  has no
Value:       unacceptable consequences to assets from security threats

**Comment by SethRedwine** [comment]
The client allows only authorized users access.
The client will save files securely.
The client's communication with external servers will be secure.

**Comment by SethRedwine** [comment]
The client will protect emails from being viewed remotely.

**Comment by SethRedwine** [comment]
The client will protect the identities of the sending and receiving parties.

**Comment by jallen3095** [comment]
The client will provide secure remote access to the contents.
