### ISSUE TITLE
Identify Bad Actors and Mis-Use Cases

### ISSUE THREAD

**Issue by ahassing** [SethRedwine/CSCI8420-TeamASJY#6]

**Comment by ahassing** [comment]
Bad Actors: 
- Law enforcement
- Rival journalists 
- Managers of journalists

**Comment by SethRedwine** [comment]
- Disgruntled article subjects

**Comment by ahassing** [comment]
Attack types:
- Watching network traffic
- Access to client on local machine
- Executable scripts in e-mails
- Tampered attachments 
- Keyloggers

**Comment by ahassing** [comment]
Available access to system
- Monitored network traffic
- Physical access to computer that the client is on
